// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvN4CbYZUH3jtw2k2Cm-wmAFpoiTuAk74',
    appId: '1:740380868295:web:4e30f84b68cf3a669988e2',
    messagingSenderId: '740380868295',
    projectId: 'fir-crashlytics-easynotes',
    authDomain: 'fir-crashlytics-easynotes.firebaseapp.com',
    storageBucket: 'fir-crashlytics-easynotes.firebasestorage.app',
    measurementId: 'G-62EQMV4WP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW08cZuEBL0NxIzOu80yAmkXL7yq9sJH4',
    appId: '1:740380868295:android:c7153b3782aaa8ea9988e2',
    messagingSenderId: '740380868295',
    projectId: 'fir-crashlytics-easynotes',
    storageBucket: 'fir-crashlytics-easynotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATtG_Z49kKreffsn7jsWP6xsiaXPpysXs',
    appId: '1:740380868295:ios:4b063cbc3d2e0b6b9988e2',
    messagingSenderId: '740380868295',
    projectId: 'fir-crashlytics-easynotes',
    storageBucket: 'fir-crashlytics-easynotes.firebasestorage.app',
    iosBundleId: 'com.sherifshouaib.easynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATtG_Z49kKreffsn7jsWP6xsiaXPpysXs',
    appId: '1:740380868295:ios:7e108b393f13cd919988e2',
    messagingSenderId: '740380868295',
    projectId: 'fir-crashlytics-easynotes',
    storageBucket: 'fir-crashlytics-easynotes.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvN4CbYZUH3jtw2k2Cm-wmAFpoiTuAk74',
    appId: '1:740380868295:web:8eb10c5fbdaf30ee9988e2',
    messagingSenderId: '740380868295',
    projectId: 'fir-crashlytics-easynotes',
    authDomain: 'fir-crashlytics-easynotes.firebaseapp.com',
    storageBucket: 'fir-crashlytics-easynotes.firebasestorage.app',
    measurementId: 'G-JH78EDC0LZ',
  );
}
