
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
        firebase_app_distribution(
            app: "1:740380868295:android:c7153b3782aaa8ea9988e2",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
            android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
            testers: "amiramohamed0559@gmail.com,bassantserag45@gmail.com,azzaamer21@gmail.com",
            release_notes: "First Fastlane Firebase Distribution Youtube video!"
        )
  end
end
